import type { AnalysisResponse } from '../types/analysis'
import { formatGeneratedAt } from './formatDate'
import { buildIncidentReportFilename } from './reportFilename'

function appendEvidence(lines: string[], report: AnalysisResponse): void {
  lines.push('## Evidence', '')
  const withEvidence = report.issues.filter((issue) => issue.evidence || issue.detail)
  if (withEvidence.length === 0) {
    lines.push('_No direct log evidence cited._', '')
    return
  }
  for (const issue of withEvidence) {
    lines.push(`### ${issue.title}`)
    if (issue.source) lines.push(`- **Source:** ${issue.source}`)
    if (issue.detail) lines.push(`- **Detail:** ${issue.detail}`)
    if (issue.evidence) lines.push(`- **Log evidence:** ${issue.evidence}`)
    lines.push('')
  }
}

function appendTimeline(lines: string[], report: AnalysisResponse): void {
  lines.push('## Incident Timeline', '')
  if (report.timeline.length === 0) {
    lines.push('_No chronological events could be established._', '')
  } else {
    for (const event of report.timeline) {
      const source = event.source ? ` (${event.source})` : ''
      lines.push(`| ${event.time} | ${event.title}${source} |`)
      if (event.detail) lines.push(`| | _${event.detail}_ |`)
    }
    lines.push('')
  }
  if (report.timeline_summary) {
    lines.push(`**Overall:** ${report.timeline_summary}`, '')
  }
}

function appendRecommendations(lines: string[], report: AnalysisResponse): void {
  lines.push('## Recommendations', '')
  if (report.recommendations.length === 0) {
    lines.push('_No recommendations provided._', '')
    return
  }
  for (const [index, item] of report.recommendations.entries()) {
    lines.push(`${index + 1}. ${item.action}`)
    if (item.command) {
      lines.push('   ```bash')
      lines.push(`   ${item.command}`)
      lines.push('   ```')
    }
    lines.push('')
  }
}

/** Professional incident report layout used by companies for postmortems. */
export function buildIncidentReport(report: AnalysisResponse): string {
  const generatedLabel = formatGeneratedAt(report.generated_at)
  const rootCause = report.root_cause || report.summary

  const lines = [
    '# Incident Report',
    '',
    `**Generated:** ${generatedLabel}`,
    `**Severity:** ${report.severity}`,
    `**Health Score:** ${report.health_score} / 100`,
    `**Confidence:** ${report.confidence}`,
    '',
    '---',
    '',
    '## Executive Summary',
    '',
    report.summary,
    '',
    '## Impact',
    '',
    report.impact || report.timeline_summary || '_Impact could not be fully determined from uploaded logs._',
    '',
    '## Root Cause',
    '',
    rootCause,
    '',
  ]

  appendTimeline(lines, report)
  appendEvidence(lines, report)
  appendRecommendations(lines, report)

  if (report.uploaded_logs.length > 0) {
    lines.push('## Sources Analyzed', '')
    for (const log of report.uploaded_logs) {
      lines.push(`- ${log}`)
    }
    lines.push('')
  }

  lines.push('---', '_Generated by Server Pulse_')
  return lines.join('\n')
}

export function downloadIncidentReport(report: AnalysisResponse): void {
  const markdown = buildIncidentReport(report)
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = buildIncidentReportFilename(report.generated_at, 'md')
  link.click()
  URL.revokeObjectURL(url)
}
