import type { AnalysisResponse } from '../types/analysis'
import { formatGeneratedAt } from './formatDate'
import { buildIncidentReportFilename } from './reportFilename'

function appendTimeline(lines: string[], report: AnalysisResponse): void {
  lines.push('## Incident Timeline', '')
  if (report.timeline.length === 0) {
    lines.push('_No chronological events could be established._', '')
  } else {
    for (const event of report.timeline) {
      const source = event.source ? ` (${event.source})` : ''
      lines.push(`- **${event.time}** — ${event.title}${source}`)
      if (event.detail) {
        lines.push(`  - ${event.detail}`)
      }
    }
    lines.push('')
  }
  if (report.timeline_summary) {
    lines.push(`**Overall:** ${report.timeline_summary}`, '')
  }
}

function appendRecommendations(lines: string[], report: AnalysisResponse): void {
  lines.push('## Recommendations', '')
  if (report.recommendations.length === 0) {
    lines.push('_No recommendations provided._', '')
    return
  }
  for (const item of report.recommendations) {
    lines.push(`- ${item.action}`)
    if (item.command) {
      lines.push('  ```bash')
      lines.push(`  ${item.command}`)
      lines.push('  ```')
    }
  }
  lines.push('')
}

/** Build a downloadable Markdown health report from the API response. */
export function buildMarkdownReport(report: AnalysisResponse): string {
  const generatedLabel = formatGeneratedAt(report.generated_at)

  const lines = [
    '# Server Pulse — Health Report',
    '',
    `**Generated At:** ${generatedLabel}`,
    `**Health Score:** ${report.health_score} / 100`,
    `**Severity:** ${report.severity}`,
    `**Confidence:** ${report.confidence}`,
  ]

  if (report.confidence_reason) {
    lines.push(`**Confidence Reason:** ${report.confidence_reason}`)
  }

  lines.push('')

  if (report.risk_scores) {
    lines.push(
      '## Risk Scores',
      '',
      `| Dimension | Risk % |`,
      `| --- | --- |`,
      `| Availability | ${report.risk_scores.availability} |`,
      `| Security | ${report.risk_scores.security} |`,
      `| Storage | ${report.risk_scores.storage} |`,
      `| Memory | ${report.risk_scores.memory} |`,
      `| Networking | ${report.risk_scores.networking} |`,
      '',
    )
  }

  if (report.uploaded_logs.length > 0) {
    lines.push('## Logs Analyzed', '')
    for (const log of report.uploaded_logs) {
      lines.push(`- ${log}`)
    }
    lines.push('')
  }

  lines.push('## Summary', '', report.summary, '')

  if (report.impact) {
    lines.push('## Impact', '', report.impact, '')
  }
  if (report.root_cause) {
    lines.push('## Root Cause', '', report.root_cause, '')
  }

  appendTimeline(lines, report)

  lines.push('## Detected Issues', '')

  if (report.issues.length === 0) {
    lines.push('_No issues detected._', '')
  } else {
    for (const issue of report.issues) {
      lines.push(`### ${issue.title}`)
      lines.push(`- **Severity:** ${issue.severity}`)
      if (issue.source) {
        lines.push(`- **Source:** ${issue.source}`)
      }
      if (issue.detail) {
        lines.push(`- **Detail:** ${issue.detail}`)
      }
      if (issue.evidence) {
        lines.push(`- **Evidence:** ${issue.evidence}`)
      }
      lines.push('')
    }
  }

  appendRecommendations(lines, report)

  if (report.suggested_logs.length > 0) {
    lines.push('## Suggested Additional Logs', '')
    for (const log of report.suggested_logs) {
      lines.push(`- ${log}`)
    }
    lines.push('')
  }

  lines.push('---', '_Generated by Server Pulse_')
  return lines.join('\n')
}

export function downloadMarkdownReport(report: AnalysisResponse): void {
  const markdown = buildMarkdownReport(report)
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = buildIncidentReportFilename(report.generated_at, 'md')
  link.click()
  URL.revokeObjectURL(url)
}
