import type { AnalysisResponse } from '../types/analysis'

/** Build a downloadable Markdown incident report from the API response. */
export function buildMarkdownReport(report: AnalysisResponse): string {
  const lines = [
    '# ServerPulse AI — Incident Report',
    '',
    `**Health Score:** ${report.health_score} / 100`,
    `**Severity:** ${report.severity}`,
    '',
    '## Summary',
    '',
    report.summary,
    '',
    '## Detected Issues',
    '',
  ]

  if (report.issues.length === 0) {
    lines.push('_No issues detected._', '')
  } else {
    for (const issue of report.issues) {
      lines.push(`### ${issue.title}`)
      lines.push(`- **Severity:** ${issue.severity}`)
      if (issue.source) {
        lines.push(`- **Source:** ${issue.source}`)
      }
      if (issue.detail) {
        lines.push(`- **Detail:** ${issue.detail}`)
      }
      if (issue.evidence) {
        lines.push(`- **Evidence:** ${issue.evidence}`)
      }
      lines.push('')
    }
  }

  lines.push('## Recommendations', '')
  if (report.recommendations.length === 0) {
    lines.push('_No recommendations provided._', '')
  } else {
    for (const item of report.recommendations) {
      lines.push(`- ${item}`)
    }
    lines.push('')
  }

  lines.push('---', '_Generated by ServerPulse AI_')
  return lines.join('\n')
}

export function downloadMarkdownReport(report: AnalysisResponse): void {
  const markdown = buildMarkdownReport(report)
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `serverpulse-report-${new Date().toISOString().slice(0, 10)}.md`
  link.click()
  URL.revokeObjectURL(url)
}
